# Change the prefix key
set -g prefix C-a

#Unbind default prefix key
unbind C-b

# Bind the new prefix key
bind C-a send-prefix 

set -g mouse on
# https://github.com/tmux-plugins/tmux-sensible
# Everything below is from the above link
set -s escape-time 0

set -g status-interval 5

set -g default-terminal "screen-256color"

set -g status-keys emacs

bind C-p previous-window
bind C-n next-window
